// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYCCkT3yYTMa-swApbllaMksCBaAFjxII',
    appId: '1:865618939896:web:106193d80187fb1d7c100d',
    messagingSenderId: '865618939896',
    projectId: 'ride-51be6',
    authDomain: 'ride-51be6.firebaseapp.com',
    storageBucket: 'ride-51be6.firebasestorage.app',
    measurementId: 'G-5MM1CT5Z71',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAl460a9RVG5IaAsgjTJA_bkUHTfkjqCVc',
    appId: '1:865618939896:android:bb4fdb535845618a7c100d',
    messagingSenderId: '865618939896',
    projectId: 'ride-51be6',
    storageBucket: 'ride-51be6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHP_yC8CY15P5DaYOJTcBoM2da6dQbns8',
    appId: '1:865618939896:ios:e58ab4e13435fcf67c100d',
    messagingSenderId: '865618939896',
    projectId: 'ride-51be6',
    storageBucket: 'ride-51be6.firebasestorage.app',
    iosBundleId: 'com.example.gibelbibela',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnUC2AoRqjgjjLXrM6uHV3fxOr9mTLj8o',
    appId: '1:865618939896:ios:9858395c9056338f7c100d',
    messagingSenderId: '865618939896',
    projectId: 'ride-51be6',
    storageBucket: 'ride-51be6.firebasestorage.app',
    iosBundleId: 'com.rideapp.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYCCkT3yYTMa-swApbllaMksCBaAFjxII',
    appId: '1:865618939896:web:227fe287596d5e8c7c100d',
    messagingSenderId: '865618939896',
    projectId: 'ride-51be6',
    authDomain: 'ride-51be6.firebaseapp.com',
    storageBucket: 'ride-51be6.firebasestorage.app',
    measurementId: 'G-ZL9J34J3VG',
  );
}